import type { ProgressBias } from '@/lib/engine/engine'

/**
 * The built-in five-day training program.
 *
 * Stored in camelCase; lib/data/program-write.ts maps it to Supabase rows.
 * Pull-ups use targetRir=0 to encode "to failure" while remaining bodyweight,
 * so the progression engine never adds load automatically.
 */
export interface SeedSlot {
  slotCode: string
  orderIndex: number
  exerciseName: string
  muscleArea: string | null
  progressBias: ProgressBias
  repLow: number
  repHigh: number
  targetRir: number
  baseSets: number
  loadIncrement: number
  seedLoad: number | null
  /** Optional; defaults to false. True only for genuine bodyweight movements. */
  isBodyweight?: boolean
}

export interface SeedDay {
  dayNumber: number
  label: string
  slots: SeedSlot[]
}

export interface SeedProgram {
  name: string
  lengthWeeks: number
  deloadWeek: number
  days: SeedDay[]
}

export const DEFAULT_PROGRAM: SeedProgram = {
  name: 'Five-Day Progression',
  lengthWeeks: 5,
  deloadWeek: 5,
  days: [
    {
      dayNumber: 1,
      label: 'Day 1 · Chest / Back',
      slots: [
        {
          slotCode: 'D1A1',
          orderIndex: 0,
          exerciseName: 'Barbell Bench Press',
          muscleArea: 'Chest',
          progressBias: 'Reps first',
          repLow: 5,
          repHigh: 10,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
        },
        {
          slotCode: 'D1A2',
          orderIndex: 1,
          exerciseName: 'Incline Dumbbell Bench Press',
          muscleArea: 'Upper chest',
          progressBias: 'Reps first',
          repLow: 6,
          repHigh: 12,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
        },
        {
          slotCode: 'D1A3',
          orderIndex: 2,
          exerciseName: 'Pull-Up',
          muscleArea: 'Back',
          progressBias: 'Reps first',
          repLow: 5,
          repHigh: 20,
          targetRir: 0,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
          isBodyweight: true,
        },
        {
          slotCode: 'D1A4',
          orderIndex: 3,
          exerciseName: 'Barbell Row',
          muscleArea: 'Back',
          progressBias: 'Reps first',
          repLow: 6,
          repHigh: 10,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
        },
        {
          slotCode: 'D1A5',
          orderIndex: 4,
          exerciseName: 'Dumbbell Lateral Raise',
          muscleArea: 'Side delts',
          progressBias: 'Reps first',
          repLow: 8,
          repHigh: 15,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 2.5,
          seedLoad: null,
        },
        {
          slotCode: 'D1A6',
          orderIndex: 5,
          exerciseName: 'Dumbbell Wrist Curl',
          muscleArea: 'Forearms',
          progressBias: 'Reps first',
          repLow: 10,
          repHigh: 20,
          targetRir: 2,
          baseSets: 3,
          loadIncrement: 2.5,
          seedLoad: null,
        },
      ],
    },
    {
      dayNumber: 2,
      label: 'Day 2 · Arms',
      slots: [
        {
          slotCode: 'D2A1',
          orderIndex: 0,
          exerciseName: 'EZ-Bar Curl',
          muscleArea: 'Biceps',
          progressBias: 'Reps first',
          repLow: 6,
          repHigh: 12,
          targetRir: 2,
          baseSets: 4,
          loadIncrement: 2.5,
          seedLoad: null,
        },
        {
          slotCode: 'D2A2',
          orderIndex: 1,
          exerciseName: 'Triceps Pushdown',
          muscleArea: 'Triceps',
          progressBias: 'Reps first',
          repLow: 6,
          repHigh: 10,
          targetRir: 2,
          baseSets: 3,
          loadIncrement: 2.5,
          seedLoad: null,
        },
        {
          slotCode: 'D2A3',
          orderIndex: 2,
          exerciseName: 'Cable Reverse Curl',
          muscleArea: 'Biceps / forearms',
          progressBias: 'Reps first',
          repLow: 8,
          repHigh: 15,
          targetRir: 2,
          baseSets: 3,
          loadIncrement: 2.5,
          seedLoad: null,
        },
        {
          slotCode: 'D2A4',
          orderIndex: 3,
          exerciseName: 'Cable Crunch',
          muscleArea: 'Abs',
          progressBias: 'Reps first',
          repLow: 8,
          repHigh: 15,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
        },
      ],
    },
    {
      dayNumber: 3,
      label: 'Day 3 · Back / Chest / Shoulders',
      slots: [
        {
          slotCode: 'D3A1',
          orderIndex: 0,
          exerciseName: 'Pull-Up',
          muscleArea: 'Back',
          progressBias: 'Reps first',
          repLow: 5,
          repHigh: 20,
          targetRir: 0,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
          isBodyweight: true,
        },
        {
          slotCode: 'D3A2',
          orderIndex: 1,
          exerciseName: 'Barbell Row',
          muscleArea: 'Back',
          progressBias: 'Reps first',
          repLow: 6,
          repHigh: 10,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
        },
        {
          slotCode: 'D3A3',
          orderIndex: 2,
          exerciseName: 'Incline Dumbbell Bench Press',
          muscleArea: 'Upper chest',
          progressBias: 'Reps first',
          repLow: 6,
          repHigh: 12,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
        },
        {
          slotCode: 'D3A4',
          orderIndex: 3,
          exerciseName: 'Cable Lateral Raise',
          muscleArea: 'Side delts',
          progressBias: 'Reps first',
          repLow: 8,
          repHigh: 15,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 2.5,
          seedLoad: null,
        },
        {
          slotCode: 'D3A5',
          orderIndex: 4,
          exerciseName: 'Dumbbell Wrist Curl',
          muscleArea: 'Forearms',
          progressBias: 'Reps first',
          repLow: 10,
          repHigh: 15,
          targetRir: 2,
          baseSets: 3,
          loadIncrement: 2.5,
          seedLoad: null,
        },
      ],
    },
    {
      dayNumber: 4,
      label: 'Day 4 · Legs / Arms',
      slots: [
        {
          slotCode: 'D4A1',
          orderIndex: 0,
          exerciseName: 'Barbell Squat',
          muscleArea: 'Quads',
          progressBias: 'Reps first',
          repLow: 6,
          repHigh: 12,
          targetRir: 2,
          baseSets: 3,
          loadIncrement: 5,
          seedLoad: null,
        },
        {
          slotCode: 'D4A2',
          orderIndex: 1,
          exerciseName: 'Deadlift',
          muscleArea: 'Hamstrings',
          progressBias: 'Reps first',
          repLow: 5,
          repHigh: 8,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
        },
        {
          slotCode: 'D4A3',
          orderIndex: 2,
          exerciseName: 'Incline Dumbbell Curl',
          muscleArea: 'Biceps',
          progressBias: 'Reps first',
          repLow: 10,
          repHigh: 15,
          targetRir: 2,
          baseSets: 3,
          loadIncrement: 2.5,
          seedLoad: null,
        },
        {
          slotCode: 'D4A4',
          orderIndex: 3,
          exerciseName: 'Skull Crusher',
          muscleArea: 'Triceps',
          progressBias: 'Reps first',
          repLow: 10,
          repHigh: 15,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 2.5,
          seedLoad: null,
        },
      ],
    },
    {
      dayNumber: 5,
      label: 'Day 5 · Shoulders / Back / Forearms',
      slots: [
        {
          slotCode: 'D5A1',
          orderIndex: 0,
          exerciseName: 'Cable Lateral Raise',
          muscleArea: 'Side delts',
          progressBias: 'Reps first',
          repLow: 10,
          repHigh: 15,
          targetRir: 2,
          baseSets: 3,
          loadIncrement: 2.5,
          seedLoad: null,
        },
        {
          slotCode: 'D5A2',
          orderIndex: 1,
          exerciseName: 'Seated Dumbbell Lateral Raise',
          muscleArea: 'Side delts',
          progressBias: 'Reps first',
          repLow: 6,
          repHigh: 12,
          targetRir: 2,
          baseSets: 2,
          loadIncrement: 2.5,
          seedLoad: null,
        },
        {
          slotCode: 'D5A3',
          orderIndex: 2,
          exerciseName: 'Pull-Up',
          muscleArea: 'Back',
          progressBias: 'Reps first',
          repLow: 5,
          repHigh: 20,
          targetRir: 0,
          baseSets: 2,
          loadIncrement: 5,
          seedLoad: null,
          isBodyweight: true,
        },
        {
          slotCode: 'D5A4',
          orderIndex: 3,
          exerciseName: 'Dumbbell Wrist Curl',
          muscleArea: 'Forearms',
          progressBias: 'Reps first',
          repLow: 10,
          repHigh: 15,
          targetRir: 2,
          baseSets: 3,
          loadIncrement: 2.5,
          seedLoad: null,
        },
      ],
    },
  ],
}
